"""empty message

Revision ID: f03136b50ec9
Revises: 
Create Date: 2019-10-30 15:03:47.034059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f03136b50ec9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_token',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('jti', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'jti')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_token')
    # ### end Alembic commands ###
